resolver: lts-6.2

# Local packages, usually specified by relative directory name
packages:
- '.'
- src/fix-agda-whitespace/
- src/hTags/
- src/size-solver/
#- test/ #Dead

extra-deps:
- vcs-revision-0.0.2
